apiVersion: v2
appVersion: 2022.04.3
icon: https://github.com/pi-hole/graphics/raw/master/Vortex/Vortex_Vertical_wordmark_lightmode.png?raw=true)
description: DNS and Ad-filtering for your network.
name: pihole
version: 1.0.6
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
home: https://pi-hole.net/
keywords:
- networking
- dns
